site_name: Geopypi
site_description: This is a python package for batch geoprocessing.

**This is a python package for batch geoprocessing.**
## Introduction
Gopypi is a Python package that allows users to analyze and visualize geospatial data using minimal code within a Jupyter environment, including platforms like Google Colab, Jupyter Notebook, and JupyterLab. It offers several interactive tools that enable users to add vector and raster data to maps without the need for coding

## Usage



- Displaying raster data: Geopypi allows you to load and display raster data, such as GeoTIFFs, on the map. This feature is useful for visualizing satellite imagery, digital elevation models, and other gridded datasets.

- Vector data display: Geopypi is compatible with multiple vector data formats such as Shapefile, GeoJSON, GeoPackage, and any format supported by GeoPandas. It allows for the loading and displaying of vector data on the map, facilitating the visualization and analysis of spatial features
  
- Downloading and visualizing data: Geopypi enables the download and visualization of geospatial data, offering detailed world imagery for diverse analytical purposes
  
- Developing interactive web applications: Geopypi facilitates the creation of interactive web apps through the use of frameworks such as Streamlit.


site_author: Metaliguns77
site_url: https://Metaliguns77.github.io/Geopypi
repo_url: https://github.com/Metaliguns77/Geopypi

copyright: "Copyright &copy; 2024 - 2024 KH Shakibul Islam"

theme:
    palette:
        - scheme: default
          #   primary: blue
          #   accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    name: material
    icon:
        repo: fontawesome/brands/github
    # logo: assets/logo.png
    # favicon: assets/favicon.png
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.top
        - search.highlight
        - search.share
    custom_dir: "docs/overrides"
    font:
        text: Google Sans
        code: Regular

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - git-revision-date-localized:
          enable_creation_date: true
          type: timeago
    # - pdf-export
    - mkdocs-jupyter:
          include_source: True
          ignore_h1_titles: True
          execute: false
          allow_errors: false
          ignore: ["conf.py"]
          execute_ignore: ["examples/KH_Shakibul_Islam_lab4.ipynb","examples/KH_Shakibul_Islam_lab5.ipynb" ]
          
markdown_extensions:
    - admonition
    - abbr
    - attr_list
    - def_list
    - footnotes
    - meta
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/Metaliguns77/Geopypi/issues
    - Examples:
        - examples/intro.ipynb
        - examples/KH_Shakibul_Islam_lab4.ipynb
        - examples/KH_Shakibul_Islam_lab5.ipynb
        - examples/KH_Shakibul_Islam_lab6.ipynb
        - examples/vector.ipynb
        - examples/raster.ipynb
        - examples/ipywegets.ipynb
        - examples/folium.ipynb
        - examples/codliver.ipynb

    - API Reference:
          - geopypi module: geopypi.md
          - common module: common.md

    
